services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: always
    environment:
      - DOMAIN=https://vault.dm-home.de
      - SIGNUPS_ALLOWED=true
      - ADMIN_TOKEN=VOWagVvQWBQcPu71C1mC/1OiXcbYILpFOYK2arn6FEBd6yzxqRraNfr5j2bcywmx
    volumes:
      - ./data:/data
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.routers.vaultwarden.rule=Host(`vault.dm-home.de`)"
      - "traefik.http.routers.vaultwarden.entrypoints=websecure"
      - "traefik.http.routers.vaultwarden.tls.certresolver=letsencrypt"
      - "traefik.http.services.vaultwarden.loadbalancer.server.port=80"

networks:
  web:
    external: true
