services:
  nextcloud:
    image: nextcloud:32-apache
    container_name: nextcloud
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=${NEXTCLOUD_DB_NAME}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - REDIS_HOST=redis
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - NEXTCLOUD_TRUSTED_DOMAINS=cloud.dm-home.de
      - OVERWRITEHOST=cloud.dm-home.de
      - OVERWRITEPROTOCOL=https
    volumes:
      - /srv/nextcloud/app:/var/www/html
      - /srv/nextcloud/data:/var/www/html/data
      - /mnt/object-storage/data/nextcloud:/mnt/object-storage:ro
    networks:
      - web
      - database
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.routers.nextcloud.rule=Host(`cloud.dm-home.de`)"
      - "traefik.http.routers.nextcloud.entrypoints=websecure"
      - "traefik.http.routers.nextcloud.tls.certresolver=letsencrypt"
      - "traefik.http.services.nextcloud.loadbalancer.server.port=80"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/status.php"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  web:
    external: true
  database:
    external: true