services:
  traefik:
    image: traefik:v3.7.0-rc.2
    container_name: traefik
    restart: always
    env_file:
      - .env
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./traefik.yml:/etc/traefik/traefik.yml:ro
      - /srv/proxy/dynamic:/etc/traefik/dynamic:ro
      - /srv/proxy/logs:/var/log/traefik
      - ./entrypoint.sh:/entrypoint.sh:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    entrypoint: ["/entrypoint.sh"]
    command: ["/docker-entrypoint.sh", "--config-file=/etc/traefik/traefik.yml"]
    networks:
      - web
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:80/ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    ulimits:
      nofile:
        soft: 65536
        hard: 65536

networks:
  web:
    external: true