global:
  checkNewVersion: true
  sendAnonymousUsage: false

api:
  dashboard: true
  insecure: true

log:
  level: INFO
  format: common

ping:
  entryPoint: web

entrypoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
  file:
    directory: /etc/traefik/dynamic
    watch: true

certificatesResolvers:
  letsencrypt:
    acme:
      email: dmytro.prylutskyi@outlook.com
      storage: /etc/traefik/acme.json
      httpChallenge:
        entryPoint: web
      tlsChallenge: true