services:
  mail:
    image: mailcow/mailcow-dockerized:2026-03
    container_name: mail
    restart: always
    ports:
      - "${SMTP_PORT}:25"
      - "${SMTPS_PORT}:465"
      - "${SUBMISSION_PORT}:587"
      - "${IMAP_PORT}:143"
      - "${IMAPS_PORT}:993"
      - "${POP_PORT}:110"
      - "${POPS_PORT}:995"
      - "${SIEVE_PORT}:4190"
      - "${DOVEVOT_PORT}:9993"

    volumes:
      - ./data/mail/data:/var/lib/docker
      - ./data/mail/mail:/var/mail
      - ./data/mail/postfix:/var/spool/postfix
      - ./data/mail/dovecot:/var/lib/dovecot
      - ./data/mail/redis:/var/lib/redis
      - ./data/mail/filter:/var/milterd
      - ./data/mail/solr:/var/lib/solr
      - ./data/mail/mysql:/var/lib/mysql
    env_file:
      - ./mail.env
    dns:
      - 127.0.0.1
    networks:
      - web
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    shm_size: 128m
    security_opt:
      - no-new-privileges:true
    environment:
      TZ: Europe/Berlin
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4G
    # labels:
    #   - "traefik.enable=true"
    #   - "traefik.http.routers.mailcow.rule=Host(`mail.example.com`)"
    #   - "traefik.http.routers.mailcow.entrypoints=websecure"
    #   - "traefik.http.routers.mailcow.tls.certresolver=letsencrypt"
    #   - "traefik.http.services.mailcow.loadbalancer.server.port=80"

networks:
  web:
    external: true