http:
  middlewares:
    security-headers:
      headers:
        sslRedirect: true
        sts_seconds: 31536000
        sts_include_subdomains: true
        sts_preload: true
        force_sts_header: true
        content_type_nosniff: true
        browser_xss_filter: true
        referrer_policy: "strict-origin-when-cross-origin"
        custom_frame_options_value: "SAMEORIGIN"
        custom_response_headers:
          X-Robots-Tag: "noindex, nofollow, noarchive"
    rate-limit:
      rate_limit:
        average: 100
        burst: 50
        period: 1s
    auth_basic:
      basicAuth:
        users:
          - "admin:$apr1$bkrbnV00$ea6PPfIrvTFjnZCzjdyDq1"